FROM python:3.10-slim

WORKDIR /gateway

COPY ./requirements.txt /gateway/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /gateway/requirements.txt

COPY ./gateway /gateway

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]